### ISSUE TITLE
Bot does not mention correctly

### ISSUE THREAD

**Issue by Spigushe** [lionel-panhaleux/timer#1]
# What is happening
The member that paused the timer did not get mentioned but their ID has been plain written
<img width="355" alt="Capture d’écran 2021-03-16 à 22 11 18" src="https://user-images.githubusercontent.com/6403098/111380417-9b1c1700-86a4-11eb-9a3a-4c1bf88708be.png">

# What it should do
The member should be mentioned and their ID should not be visible

# How to fix it
The mention from member ID is built `<@member_id>` and it should resolve the issue

**Comment by Spigushe** [comment]
Suggestion [bot.py Line 237](https://github.com/lionel-panhaleux/timer/blob/89e7e2bba43bcb92410988be5fb78ea7accf38ff/src/timer_bot.py#L237):
```diff
- f"{self.author.mention} paused by {user.mention if user else user_id}"
+ f"{self.author.mention} paused by {user.mention if user else '<@'+user_id+'>'}"
```

**Comment by lionel-panhaleux** [comment]
Happy to try this fix, but hopefully you can reproduce? if `user` is `None`, this means `user = client.get_user(user_id)` didn't work, so I'm curious about how that happens. Not sure the `<@user_id>` syntax will fix it, but there's no downside in trying.

**Comment by Spigushe** [comment]
I did reproduce the bug and it is fixed ! 🥳 
<img width="303" alt="Capture_decran_2021-03-17_a_12 59 04" src="https://user-images.githubusercontent.com/6403098/111464683-67cb9d80-8721-11eb-967d-1da6efb136a3.png">
